# Generated by Django 5.2.9 on 2025-12-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_useraddresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddresses',
            name='is_Default',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
