# Generated by Django 5.2.9 on 2025-12-20 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='total_price',
        ),
    ]
