# Generated by Django 5.2.9 on 2025-12-28 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_color_size_product_status_alter_product_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'رنگ', 'verbose_name_plural': 'رنگ'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'اندازه', 'verbose_name_plural': 'اندازه'},
        ),
    ]
